/**
 * This file was auto-generated by the Titanium Module SDK helper for Android
 * Appcelerator Titanium Mobile
 * Copyright (c) 2009-2010 by Appcelerator, Inc. All Rights Reserved.
 * Licensed under the terms of the Apache Public License
 * Please see the LICENSE included with this distribution for details.
 *
 */
package firebase.analytics;

import org.appcelerator.kroll.KrollDict;
import org.appcelerator.kroll.KrollModule;
import org.appcelerator.kroll.common.Log;
import org.appcelerator.kroll.common.TiConfig;
import org.appcelerator.kroll.annotations.Kroll;

import org.appcelerator.titanium.TiApplication;
import org.appcelerator.titanium.util.TiConvert;

import android.os.Bundle;

import com.google.firebase.analytics.FirebaseAnalytics;
import com.google.firebase.analytics.FirebaseAnalytics.Param;

@Kroll.module(name="TitaniumFirebaseAnalytics", id="firebase.analytics")
public class TitaniumFirebaseAnalyticsModule extends KrollModule
{
	private static final String LCAT = "TitaniumFirebaseAnalyticsModule";
	private static final boolean DBG = TiConfig.LOGD;
  private static FirebaseAnalytics mFirebaseAnalytics;

	public TitaniumFirebaseAnalyticsModule()
	{
		super();
	}
  
  private FirebaseAnalytics analyticsInstance()
  {
    if (this.mFirebaseAnalytics == null) {
      this.mFirebaseAnalytics = FirebaseAnalytics.getInstance(getActivity().getApplicationContext());
    }
    
    return this.mFirebaseAnalytics;
  }

  @Kroll.method
  public void log(String name, KrollDict parameters)
  {
    Bundle bundle = new Bundle();

    // TODO: Loop through all keys and set accordingly
    if (parameters.containsKey(Param.ACHIEVEMENT_ID)) {
      bundle.putString(Param.ACHIEVEMENT_ID, TiConvert.toString(parameters, Param.ACHIEVEMENT_ID));
    }

    this.analyticsInstance().logEvent(name, bundle);
  }

  @Kroll.method @Kroll.setProperty
  public void setUserPropertyString(KrollDict parameters)
  {
    this.analyticsInstance().setUserProperty(TiConvert.toString(parameters, "name"), TiConvert.toString(parameters, "value"));
  }

  @Kroll.method @Kroll.setProperty
  public void setScreenNameAndScreenClass(KrollDict parameters)
  {
    if (parameters.containsKey("screenName")) {
      this.analyticsInstance().setCurrentScreen(getActivity(), TiConvert.toString(parameters, "screenName"), null);
    } else {
      Log.e(LCAT, "Unable to set current screen without the missing \"screenName\" key");
    }
  }
}
